In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math

In [3]:
cities =['Shanghai', 'Beijing','Istanbul']
population =[24183300,20794100,15030000]

In [5]:
cityPop = pd.Series(population, cities)
cityPop

Shanghai    24183300
Beijing     20794100
Istanbul    15030000
dtype: int64

In [6]:
cityPop = pd.Series(index=cities, data=population)
cityPop

Shanghai    24183300
Beijing     20794100
Istanbul    15030000
dtype: int64

In [7]:
cityPop.sum()

60007400

In [9]:
cityPop.mean()

20002466.666666668

In [10]:
cityPop.values

array([24183300, 20794100, 15030000], dtype=int64)

In [11]:
cityPop.get_values()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The 'get_values' method is deprecated and will be removed in a future version. Use '.to_numpy()' or '.array' instead.
  """Entry point for launching an IPython kernel.


array([24183300, 20794100, 15030000], dtype=int64)

In [12]:
cityPop.to_numpy()

array([24183300, 20794100, 15030000], dtype=int64)

In [13]:
cityPop.index

Index(['Shanghai', 'Beijing', 'Istanbul'], dtype='object')

In [14]:
cityPop.keys()

Index(['Shanghai', 'Beijing', 'Istanbul'], dtype='object')